version: '3.8'
services: 
  web: 
    image: nate1504/tcmg412
    ports: 
      - '5000:5000'
    networks: 
      - webnet
  redis: 
    image: redis
    networks: 
      - webnet
networks: 
  webnet: